### PR TITLE
Refactor AddressBook to ModuleTracker

### PR DESCRIPTION
**Pull request by tingyic**

### CODE REVIEW

**Comment by tingyic** [comment]
WIP. Trying to refactor slowly so that it can be merged without complex merge conflict

**Comment by tingyic** [comment]
> 

Resolved! Finally!

**Review by jayhee3 — APPROVED** [review]
LGTM! There was one merge conflict but it has since been fixed.

**Comment by jayhee3** [comment]
Thanks for the detailed changes.

**Pull request merged**
